---

- name: Create home folders
  user:
    name: "{{ item['user'] }}"
    state: present
    createhome: yes
    shell: /bin/bash
  with_items: vhost_sites
  sudo: yes

- name: Create public_html folders
  file:
    path: /var/www/{{ item['host'] }}/
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Create public_html symlinks
  file:
    dest: /var/www/{{ item['host'] }}/public_html
    src: /home/{{ item['user'] }}/public
    state: link
  with_items: vhost_sites

- name: Create log folders
  file:
    path: /var/log/apache2/{{ item['host'] }}/
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Create logs symlinks
  file:
    src: /var/log/apache2/{{ item['host'] }}
    dest: /home/{{ item['user'] }}/logs
    state: link
  with_items: vhost_sites

- name: Create vhosts
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item['host'] }}.conf
  with_items: vhost_sites

- name: Enable vhosts
  file:
    src: /etc/apache2/sites-available/{{ item['host'] }}.conf
    dest: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: link
  with_items: vhost_sites
  notify: Restart Apache