---
- name: Delete user
  user:
    name: "{{ item['user'] }}"
    state: absent
    remove: yes
  with_items: deleted_vhost_sites

- name: Delete public_html folders
  file:
    path: /srv/www/{{ item['host'] }}
    state: absent
  with_items: deleted_vhost_sites

- name: Disable vhosts
  file:
    path: /etc/apache2/sites-enabled/{{ item['host'] }}.conf
    state: absent
  with_items: deleted_vhost_sites
  notify: Restart Apache

- name: Delete vhosts
  file:
    path: /etc/apache2/sites-available/{{ item['host'] }}.conf
    state: absent
  with_items: deleted_vhost_sites
  notify: Restart Apache
